name       : haskell-type-equality
version    : 1.0
release    : 1
source     :
    - https://hackage.haskell.org/package/type-equality-1/type-equality-1.tar.gz : 4728b502a211454ef682a10d7a3e817c22d06ba509df114bb267ef9d43a08ce8
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library defines a propositional equality data types
description: |
    This library defines a propositional equality data type, shims Data.Type.Equality as well as possible for older GHCs (< 7.8).
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
